Add connector to support Niconico
web-scrobbler/web-scrobbler pull request #2711
Opened 2021-01-16 17:36 UTC by takagiy

**Describe the changes you made**
This request is going to add support for Niconico (www.nicovideo.jp), a popular video streaming service in japan, by setting up a new connector.

**Additional context**
RE: #1932

2021-01-17 08:17 UTC, takagiy commented
Oh, I missed `src/core/content/util.js`. Maybe, should I do some refactoring?

2021-01-17 10:01 UTC, alexesprit requested changes

2021-01-17 10:02 UTC, alexesprit commented
> Oh, I missed src/core/content/util.js (looks useful for filtering). Maybe, should I do some refactoring?

What do you want to use from this module?

2021-01-17 10:32 UTC, takagiy commented on src/connectors/nicovideo.js
> +	return text.replaceAll(decorationPattern, '').replace(extraInfoPattern, '');
Thanks you.
fix: b7da50a

2021-01-17 11:43 UTC, takagiy commented
@alexesprit I'll try to replace [this matching](https://github.com/takagiy/web-scrobbler/blob/b7da50aaea379aad6807e69ed0cd59f0a003601b/src/connectors/nicovideo.js#L32-L33) with `Util.splitString()` or `Util.splitArtistTrack` if you prefer it. But I think the regex pattern can do bit more complex (e.g. requiring some kind of whitespace before `feat.`, treating `-` surrounded by non-alphanumerics as separators, but not those that aren't and using `/` at the most right as separators).

2021-01-17 11:51 UTC, alexesprit commented
It's fine to use regular expressions here.

2021-01-17 11:56 UTC, takagiy commented
I see, I'll leave it as it is. Thank you.

2021-01-17 15:20 UTC, takagiy commented
I noticed that when I switched my language setting to Japanese, Niconico shows artist name with -さん suffix like "Artist さん". I'll modify the filter to remove that.

2021-01-18 05:08 UTC, alexesprit approved these changes

2021-01-18 05:09 UTC, merged