Add Stingray Music Connector
web-scrobbler/web-scrobbler pull request #2779
Opened 2021-03-19 14:16 UTC by jbwharris

**Describe the changes you made**
Create connector for Stingray Music

**Additional context**
https://www.stingray.com/
This one works well if you're using an ad blocker like uBlock Origin, but I had noted issues with being a track behind when it did ad insertion that I wasn't able to figure out how to reconcile that.

2021-03-22 05:25 UTC, alexesprit requested changes
This website contains additional information you could add to the connector:
1. Album name
2. Cover art
3. Play/pause button

2021-03-22 05:26 UTC, alexesprit commented on src/core/connectors.js
> +		'*://webplayer.stingray.com/*',
I would replace this pattern with `*.stingray.com/*` to let the extension mark the main website (stingray.com) as supported.

2021-04-03 16:35 UTC, jbwharris commented
@alexesprit I have made the suggested changes.

2021-04-04 07:20 UTC, alexesprit commented on src/connectors/stingray.js
> +Connector.getTrackArt = () => Util.extractUrlFromCssProperty(document.querySelector('cover-with-info.current.cover div.background').style['background-image']);
Default implementation has already this logic. Using `Connector.trackArtSelector` property is enough here.

2021-04-04 07:24 UTC, alexesprit approved these changes

2021-04-04 07:24 UTC, merged