Fixed Indie88 connector
web-scrobbler/web-scrobbler pull request #3042
Opened 2021-10-29 03:16 UTC by jbwharris

**Describe the changes you made**
I discovered the Indie88 connector was broken for both player version I built the connector for. Looks like they just moved around some UI elements on their pages. 

**Additional context**
![image](https://user-images.githubusercontent.com/2962327/139369723-a8e1e7e5-7379-411a-8866-bde6d759e3f7.png)

2021-10-29 21:06 UTC, inverse commented on src/connectors/thecurrent.js
> +const filter = MetadataFilter.createFilter({
Can you undo the changes to this file 👍🏼

2021-10-29 21:06 UTC, inverse requested changes
Looks good but we should undo changes to `thecurrent.js` 👍🏼

2021-10-30 16:23 UTC, jbwharris commented
@inverse I will see if I can sort that later today.

2021-10-30 19:47 UTC, jbwharris commented
@inverse Just pushed that change

2021-10-30 19:51 UTC, inverse commented
@jbwharris I'm still seeing the changes in the branch. See the number of files changed at the top is 2

![image](https://user-images.githubusercontent.com/713525/139556702-ee73e69c-f178-43f1-b459-87b6943248dc.png)

Looks like your creating the PR from your `master` branch. Perhaps try 

- making your master match this repo master
- branch from that
- apply only the required changes to that branch
- create a PR from that

2021-11-03 23:57 UTC, jbwharris commented
@inverse I will get to sorting this out, may take until the weekend though as it's been a busy one at work

2021-11-06 16:41 UTC, jbwharris reviewed
@inverse I'm not quite sure what the the change to thecurrent.js is, since I did replace the file with the latest published version from GitHub.

2021-11-06 21:16 UTC, inverse commented
The problem I believe is because you're creating the pull requests from the `master` branch of your fork which normally would be fine for a single change.

However a better practice is to create a branch from that and create changes relevant for that change.

Depending on how you set this up you might be able to get this working with:


```bash
git checkout -B fix-indie88
git checkout master -- src/connectors/thecurrent.js
```

and then commit the undo to `src/connectors/thecurrent.js`

2021-11-11 18:02 UTC, jbwharris commented
I'm going to close this pull request and see if I can figure it out, as I can't seem to get that second file to pull back

2021-11-11 18:02 UTC, closed without merging

2021-11-11 19:38 UTC, inverse commented
No worries - take your time and let me know if you need any further help.