Fixed the connector for FluxFM web radio.
web-scrobbler/web-scrobbler pull request #3145
Opened 2022-02-22 19:48 UTC by fckawe

**Describe the changes you made**
The connector didn't work anymore after the website was redesigned.
Album info and track art aren't available anymore. Artist and title cannot be parse from separate elements.

**Additional context**
Fixes issue #3142.

2022-02-22 20:14 UTC, inverse commented on src/connectors/fluxfm.js
> +Connector.getArtistTrack = () => {
Could be simplified to

```
Connector.artistTrackSelector = '.hero-player__title';
```

2022-02-22 20:15 UTC, inverse reviewed
Looks good aside the one comment 👍🏼

2022-02-23 07:02 UTC, fckawe commented
Okay, I didn't notice that one in the documentation... :/ Thanks for the review!
I'm not sure how to change that now, since I'm not so familiar with the whole workflow. Do I have to do something at all?

2022-02-23 08:01 UTC, fckawe commented
Wait! I've made a mistake, sorry.
In my first version I took the artist - title element and separated it manually (via split). Then I've found the function to do the split artist and title.
The problem: The page is showing the title first and then the artist.
So, with that version artist and title are swapped! I didn't notice that because the music they played was quite unknown... :(
I guess I have to change it back to manually splitting...

2022-02-24 14:55 UTC, fckawe commented
Commited two more changes:

1. Using different selectors, now. That way the connector not only works with the live radio player but also with the "channels" they provide on the website.
2. Disabling scrobbling if track title is "Livestream" and artist is "FluxFM", which sometimes happens when no music is played and no upcoming track is given.

I think it works quite well, now.

2022-02-25 20:46 UTC, inverse commented on src/connectors/fluxfm.js
> +	return Util.getAttrFromSelectors('rs-play-button > rs-button > button', 'title') === 'Pausieren';
```suggestion
	return Util.getAttrFromSelectors('.playbar rs-play-button > rs-button > button', 'title') === 'Pausieren';
```

2022-02-25 20:47 UTC, inverse requested changes
Minor change but looks a lot better 👍🏼

2022-02-25 20:53 UTC, inverse approved these changes
Modified with changes after testing locally 👍🏼

2022-02-25 20:53 UTC, merged