Only scrobble one artist in YouTube Music
web-scrobbler/web-scrobbler pull request #3306
Opened 2022-07-17 20:47 UTC by AvikRao

**Describe the changes you made**
Only scrobble the first artist in Youtube Music. Last.fm, the biggest music tracking service, only allows a single artist to be credited for each song. When the Web Scrobbler scrobbles multiple artists as a comma-separated string, it breaks compatibility with many of Last.fm's social features, such as identifying which songs and artists you share in common with other users. To maintain compatibility with Last.fm's single-artist paradigm for each song, the change made in this PR only scrobbles the first artist credited on a song, rather than comma-separating the entire list. 

**Additional context**
Example of Web Scrobbler scrobbling Phoenix by "League of Legends, Cailin Russo, Chrissy Costanza":
![image](https://user-images.githubusercontent.com/38502391/179424141-80b7df46-08a0-40d1-817e-b7e1c51f8986.png)
The actual song's entry in Last.fm, only by League of Legends:
![image](https://user-images.githubusercontent.com/38502391/179424160-e2e74d25-219c-47cf-93d2-1c74dfe1b74f.png)

By observing the global scrobble count, clearly the single-artist entry is the correct one. This is not a cherrypicked example - every example I have searched for with multiple artists follows the same pattern.

2022-07-21 19:42 UTC, inverse requested changes
Looks good except we should probably change the function name to `getArtist()` to better represent. Also I think FIXME comment is no-longer valid :)

2022-07-21 22:03 UTC, jaccarmac commented
> By observing the global scrobble count, clearly the single-artist entry is the correct one. This is not a cherrypicked example - every example I have searched for with multiple artists follows the same pattern.

Two notes:

1. I don't think this is correct. It's certainly true that, in some sense "Last.fm ... only allows a single artist to be credited". But tagging collaborative work with both artists is widespread and not strictly incorrect.
2. If we want to make this change, it seems better to do it for all connectors, as it's not a YouTube Music specific problem.

To be clear, I'm against it on general grounds, but think it's especially incorrect to implement only for YouTube Music. (I don't think this would be a good case for an option and would rather see something like #2943 to allow users to customize the extension behavior. However, I understand that that is a less attractive solution.)

2022-07-21 22:04 UTC, jaccarmac reviewed
If this behavior changes, it should change globally and not only for YouTube Music. (Trivially, the YouTube connector should use the same rule.)

2022-09-27 00:31 UTC, a-github-account commented
I think this should be a togglable setting because other services that aren't Last.fm might utilize the multiple-artists approach.

2022-09-27 18:58 UTC, inverse approved these changes

2022-09-27 19:00 UTC, inverse commented
@jaccarmac do you have any further input on this one? I guess you're right that it should be made into something more generic and perhaps controlled like @a-github-account suggested.

2022-09-27 23:22 UTC, jaccarmac commented
Option or no, I maintain that the switch to single-artist behavior is incorrect if it happens only on YouTube Music. In the interest of the work that went into this PR, though, perhaps we could meet in the middle with an option which changes the behavior of YouTube *and* YouTube Music but no other connectors?

2023-04-23 22:05 UTC, yayuyokitano commented
Closing, as #3671 allows the user to achieve this if they want to in a controllable way that works across all connectors.

2023-04-23 22:05 UTC, closed without merging

2025-10-03 05:35 UTC, Lamby777 commented
> Closing, as #3671 allows the user to achieve this if they want to in a controllable way that works across all connectors.

How...? If you mean using regex to pick everything before the & sign, this ruins full artist names like `Bob Marley & The Wailers` or `King Gizzard & The Lizard Wizard` ([what did they do to the lizard??? D:](https://www.last.fm/music/King+Gizzard)). This problem is on the connector level, can't be fixed once the artists are combined...

I understand scrobbling the full list, and I used to believe this was the best option too, but this makes scrobbling certain artists that do features a lot (Gorillaz, Daft Punk, etc.) really skewed and pretty much pointless. Not to mention different platforms combining lists of artists differently ([here's](https://www.last.fm/music/Lotus+Juice,+Azumi+Takahashi,+&+ATLUS+Sound+Team/_/Mass+Destruction+-Reload-) a [game](https://www.last.fm/music/Lotus+Juice,+Azumi+Takahashi,+ATLUS+Sound+Team/_/Mass+Destruction+-Reload-) of [spot the difference](https://www.last.fm/music/Lotus+Juice,+Azumi+Takahashi+&+ATLUS+Sound+Team/_/Mass+Destruction+-Reload-), and of course [this one](https://www.last.fm/music/Lotus+Juice/_/Mass+Destruction+-Reload-) has actual comments). We should be given a setting to do what this PR does, not just assume & means another artist when the YT Music site cleanly separates multiple `<a>` tags for us when necessary. :/