Add infobox to inject scrobbling info & state into pages
web-scrobbler/web-scrobbler pull request #3861
Opened 2023-06-04 22:00 UTC by Boelensman1

**Describe the changes you made**
Add infobox to display scrobbling state on the page. My motivation is that I dislike notifications, it would also be a good solution for safari where you're apparently not allowed to send notifications.

**Additional context**
<img width="435" alt="image" src="https://github.com/web-scrobbler/web-scrobbler/assets/1338743/8ae469e5-820f-4c05-8851-0f9f5ddadfa0">

**Todo**
- [ ] Allow connectors to set custom styling
- [ ] Make optional (how do I get global options in content/connector?)
- [ ] Use translations for the scrobbling/loading etc. text
- [ ] More thorough testing

2023-06-04 22:02 UTC, Boelensman1 commented
Oops, apparently when you reload the page github changes draft pull request back into a normal one. And now I can't seem to change it into one. So just to be clear, this was supposed to be a draft...

2023-09-17 19:03 UTC, Boelensman1 commented
All right, this should be about done.

I did have the issue that the extension only started doing things after I clicked on it, but I don't think that's related to my code and might just be a bug in the dev environment?

2023-09-19 13:49 UTC, yayuyokitano commented
I have created a PR with suggested change: https://github.com/Boelensman1/web-scrobbler/pull/1

2023-09-19 13:50 UTC, yayuyokitano requested changes
In addition to the mentioned PR

2023-09-19 18:53 UTC, Boelensman1 commented on src/_locales/en_GB/messages.json
> +        "message":  "Scrobbling is not allowed due to an option",
Ah, I basically copied the comment from https://github.com/web-scrobbler/web-scrobbler/blob/7f598dc6922a25978162e6730455181ab915d97f/src/core/object/controller/controller-mode.ts#L6-L9 Do you have a suggestion for a better description of what disallowed means?

2023-09-19 21:30 UTC, yayuyokitano commented on src/_locales/en_GB/messages.json
> +        "message":  "Scrobbling is not allowed due to an option",
I dont know how to do so concisely. I think we can do one of those where we tell the user to open the popup maybe?

2023-09-19 22:37 UTC, Boelensman1 commented on src/_locales/en_GB/messages.json
> +        "message":  "Scrobbling is not allowed due to an option",
Sounds like a good idea. I tried for a bit to make the icon clickable and open the popup, which is possible but not from the content script. Would be cool for a future update.

2023-09-19 22:49 UTC, yayuyokitano commented on src/_locales/en_GB/messages.json
> +        "message":  "Scrobbling is not allowed due to an option",
Seems trivial. I'll handle it once this is merged. I'll give this another review tomorrow and try to have a look into the test issue.

2023-09-20 10:48 UTC, yayuyokitano commented
https://github.com/Boelensman1/web-scrobbler/pull/2

2023-09-20 21:00 UTC, yayuyokitano approved these changes
I feel this is good to go now. Thank you for all the work!

2023-09-20 21:01 UTC, merged