Fixed RadioParadise connector for small screens
web-scrobbler/web-scrobbler pull request #4102
Opened 2023-09-12 01:24 UTC by jbwharris

- I discovered a bug today where the RadioParadise connector wouldn't scrobble on smaller screen sizes. The site did some DOM changes that made some targeted elements disappear between desktop and mobile, so I was able to find some consistent elements to target to make it work properly.

2023-09-12 08:35 UTC, yayuyokitano requested changes
Needs to be prettified for consistency. Should be as follows:

```ts
export {};

Connector.playerSelector = '#conductor-wrapper';

Connector.albumSelector = '#now_playing .album';
Connector.artistSelector = '.player-bar .player-artist';
Connector.trackSelector = '.player-bar .player-title';

Connector.isPlaying = () => {
	return (
		Util.getAttrFromSelectors('#global-player mat-icon', 'title') ===
		'Pause'
	);
};

Connector.trackArtSelector = '.player-bar img.player-cover';

Connector.isScrobblingAllowed = () => {
	return (
		!Util.getTextFromSelectors('.player-bar .player-title')?.includes(
			'Listener-supported',
		) && !Connector.getArtist()?.startsWith('Commercial-Free')
	);
};
```
It's not caught by the CI yet pending #4097

2023-09-12 13:49 UTC, jbwharris commented
@yayuyokitano I just pushed those prettified changes. I wanted to make sure, the issue there was just double quotes instead of single quotes in my file? I just tweaked my JSPrettier settings accordingly.

2023-09-13 20:35 UTC, yayuyokitano approved these changes

2023-09-13 20:37 UTC, yayuyokitano commented
> @yayuyokitano I just pushed those prettified changes. I wanted to make sure, the issue there was just double quotes instead of single quotes in my file? I just tweaked my JSPrettier settings accordingly.

Seems so.
Thank you for the contribution! Changes look reasonable.

2023-09-13 20:37 UTC, merged