New ChirpRadio connector
web-scrobbler/web-scrobbler pull request #4695
Opened 2024-05-10 16:43 UTC by jbwharris

New connector for https://chirpradio.org

![image](https://github.com/web-scrobbler/web-scrobbler/assets/2962327/b7bfadb7-8234-4e50-a674-b92d81eee3b9)

2024-05-13 20:25 UTC, inverse requested changes
Looks good aside the additional changes in `src/core/connectors.ts`

2024-05-13 20:25 UTC, inverse commented on src/core/connectors.ts
> +	hasNativeScrobbler?: true;
This file looks like it needs to be adapted to only the addition of the connector addition

2024-05-14 13:18 UTC, jbwharris commented
@inverse I just pushed over the change to connectors.ts

2024-05-26 19:02 UTC, inverse commented
@jbwharris looks like there are still a lot of changes that shouldnt be there :thinking:

2024-05-26 19:09 UTC, closed without merging

2024-05-26 19:24 UTC, jbwharris commented
@inverse I have no idea what I've done wrong with this one. I'm going to create a new branch and do a new PR